kramdown:
  input: GFM
  hard_wrap: false

markdown:
  kramdown

baseurl: /avx2.github.io

githuburl: https://github.com/grpc/avx2.github.io/

sass:
  style: compressed
  
paginate: 2

paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->
